/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package zrrtcs.manipurassu.gui;

import javax.swing.plaf.synth.SynthLookAndFeel;
import zrrtcs.manipurassu.rubymachine.RubyMachine;

/**
 *
 * @author pzagmatic
 */
public class ManipurassuSimpleGui extends javax.swing.JFrame {
    
    private RubyMachine rubyMachine;
    private javax.swing.JTextArea outputCurrentTxtArea;
    /**
     * Creates new form ManipurassuSimpleGui
     */
    public ManipurassuSimpleGui() {
        rubyMachine = new RubyMachine();
        initComponents();
        outputTabbedPanel.setVisible(true);
        outputCurrentTxtArea = outputTxtArea1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        inputStringPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextArea();
        EastManipurassiPanel = new javax.swing.JPanel();
        rubyCodePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInputRuby = new javax.swing.JTextArea();
        buttonRubyPanel = new javax.swing.JPanel();
        btnFireRuby = new javax.swing.JButton();
        outputStringPanel = new javax.swing.JPanel();
        outputTabbedPanel = new javax.swing.JTabbedPane();
        outputPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputTxtArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setResizeWeight(0.5);

        inputStringPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("INPUT");
        inputStringPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        txtInput.setColumns(20);
        txtInput.setRows(5);
        jScrollPane1.setViewportView(txtInput);

        inputStringPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(inputStringPanel);

        EastManipurassiPanel.setLayout(new java.awt.GridLayout(2, 1));

        rubyCodePanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("RUBY");
        rubyCodePanel.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        txtInputRuby.setColumns(20);
        txtInputRuby.setRows(5);
        jScrollPane2.setViewportView(txtInputRuby);

        rubyCodePanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        buttonRubyPanel.setLayout(new java.awt.GridLayout(1, 2));

        btnFireRuby.setText("FIRE");
        btnFireRuby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFireRubyActionPerformed(evt);
            }
        });
        buttonRubyPanel.add(btnFireRuby);

        rubyCodePanel.add(buttonRubyPanel, java.awt.BorderLayout.PAGE_END);

        EastManipurassiPanel.add(rubyCodePanel);

        outputStringPanel.setLayout(new java.awt.BorderLayout());

        outputPanel1.setLayout(new java.awt.BorderLayout());

        outputTxtArea1.setColumns(20);
        outputTxtArea1.setRows(5);
        jScrollPane3.setViewportView(outputTxtArea1);

        outputPanel1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        outputTabbedPanel.addTab("output01", outputPanel1);

        outputStringPanel.add(outputTabbedPanel, java.awt.BorderLayout.CENTER);

        EastManipurassiPanel.add(outputStringPanel);

        jSplitPane1.setRightComponent(EastManipurassiPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFireRubyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFireRubyActionPerformed
        String inputTxt = this.txtInput.getText();
//        this.txtInputRuby.setText(rubyMachine.helloWorld());
        String outputTxt = rubyMachine.fireRubyStringManipulator(inputTxt, this.txtInputRuby.getText());
        outputCurrentTxtArea.setText(outputTxt);
    }//GEN-LAST:event_btnFireRubyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++)
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManipurassuSimpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManipurassuSimpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManipurassuSimpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManipurassuSimpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManipurassuSimpleGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EastManipurassiPanel;
    private javax.swing.JButton btnFireRuby;
    private javax.swing.JPanel buttonRubyPanel;
    private javax.swing.JPanel inputStringPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel outputPanel1;
    private javax.swing.JPanel outputStringPanel;
    private javax.swing.JTabbedPane outputTabbedPanel;
    private javax.swing.JTextArea outputTxtArea1;
    private javax.swing.JPanel rubyCodePanel;
    private javax.swing.JTextArea txtInput;
    private javax.swing.JTextArea txtInputRuby;
    // End of variables declaration//GEN-END:variables
}
